#!/bin/bash

if [ -z "$1" ]; then
    echo "Usage: $0 /path/to/dir"
    exit 1;
fi

if [ -d "$1" ] || [ -f "$1" ]; then
    chown "$(logname)":"$(logname)" -R "$1"
    chmod 775 -R "$1"
else
    echo "Invalid Path."
    exit 1;
fi

exit 0;
